import defaultTheme from 'tailwindcss/defaultTheme'

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    './storage/framework/views/*.php',
    './resources/views/**/*.blade.php',
    './app/Livewire/**/*.php',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#690008',
          container: '#8b1a1a',
          hover: '#4d0006',
          fixed: '#ffdad6',
          'fixed-dim': '#ffb3ac',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#ff9a91',
        'on-primary-fixed': '#410003',
        'on-primary-fixed-variant': '#8a1a1a',
        'inverse-primary': '#ffb3ac',
        secondary: {
          DEFAULT: '#735c00',
          container: '#fed65b',
          fixed: '#ffe088',
          'fixed-dim': '#e9c349',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#745c00',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        tertiary: {
          DEFAULT: '#30322a',
          container: '#474840',
          fixed: '#e4e3d7',
          'fixed-dim': '#c7c7bc',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b7b6ac',
        'on-tertiary-fixed': '#1b1c15',
        'on-tertiary-fixed-variant': '#46473f',
        surface: {
          DEFAULT: '#fcf9f8',
          dim: '#dcd9d9',
          bright: '#fcf9f8',
          variant: '#e4e2e1',
          tint: '#ac322e',
          'container': '#f0eded',
          'container-low': '#f6f3f2',
          'container-high': '#eae7e7',
          'container-highest': '#e4e2e1',
          'container-lowest': '#ffffff',
        },
        background: '#fcf9f8',
        'on-background': '#1b1c1c',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#58413f',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0f0',
        outline: {
          DEFAULT: '#8c716e',
          variant: '#e0bfbc',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'brand-error': '#ba1a1a',
        gold: {
          light: '#F9E392',
          mid: '#D4AF37',
          dark: '#996515',
          border: '#B8860B',
        },
        'industrial-gray': '#2B2B2B',
        'carbon-black': '#121212',
        'heritage-gold': '#D4AF37',
        'oxblood-red': '#690008',
      },
      fontFamily: {
        serif:        ['"Source Serif 4"', ...defaultTheme.fontFamily.serif],
        sans:         ['"Hanken Grotesk"', ...defaultTheme.fontFamily.sans],
        mono:         ['"JetBrains Mono"', ...defaultTheme.fontFamily.mono],
        display:      ['"Source Serif 4"', ...defaultTheme.fontFamily.serif],
        'headline-lg':['"Source Serif 4"', ...defaultTheme.fontFamily.serif],
        'headline-md':['"Source Serif 4"', ...defaultTheme.fontFamily.serif],
        'headline-sm':['"Source Serif 4"', ...defaultTheme.fontFamily.serif],
        'body-md':    ['"Hanken Grotesk"', ...defaultTheme.fontFamily.sans],
        'body-lg':    ['"Hanken Grotesk"', ...defaultTheme.fontFamily.sans],
        'label-bold': ['"JetBrains Mono"', ...defaultTheme.fontFamily.mono],
        'label-sm':   ['"JetBrains Mono"', ...defaultTheme.fontFamily.mono],
      },
      fontSize: {
        'display':            ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '900' }],
        'headline-lg':        ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md':        ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-sm':        ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'price':              ['20px', { lineHeight: '1', fontWeight: '700' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-bold':         ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm':           ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '2px',
        sm: '2px',
        md: '6px',
        lg: '8px',
        chip: '9999px',
        full: '9999px',
      },
      maxWidth: {
        container: '1280px',
        'container-max': '1280px',
      },
      spacing: {
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        'base': '8px',
      },
    },
  },
  plugins: [],
}
